### ISSUE TITLE
Bro puedo usar tu config para hacer un nuevo tema y ponerlo como tema colaborativo??

### ISSUE THREAD

**Issue by P4NAD3ROXIS** [kaibakev1984/Lorblak-Dotfiles#3]
Estoy haciendo sadwintosh y la config de soft es perfecta que dices pana :3

**Comment by kaibakev1984** [comment]
Sí, no hay problema. Usá todo lo que necesites. Si va a ser un tema colaborativo, lo ideal es organizarnos. ¿Venís de XUnix de casualidad? Podemos organizarnos desde ahí.

**Comment by P4NAD3ROXIS** [comment]
Pasame tu fb para hablar por hay

**Comment by 0x5add** [comment]
Bom dia amigo, pode usar simm, GPL is all !

Em ter., 8 de jun. de 2021 às 11:01, Lorblak ***@***.***>
escreveu:
