### ISSUE TITLE
Origen de los iconos / Source of the icons

### ISSUE THREAD

**Issue by HackerMan0611** [kaibakev1984/Lorblak-Dotfiles#4]
Origen / Source
----------------------------------------------------------------------------------------------
Hola,
¿Sería posible tener la fuente de los iconos utilizados para `polybar`? Los encuentro muy bonitos pero no se encuentran y me gustaría poner algunos para cada `workspace`.
Gracias de antemano (perdón si es incomprensible, he utilizado deepl)
----------------------------------------------------------------------------------------------
Hello,
Would it be possible to have the source of the icons used for `polybar`? I find them very beautiful but they are not found and I would like to put some for each `workspace`.
Thank you in advance (sorry if it is incomprehensible, I used deepl)

**Comment by kaibakev1984** [comment]
Hi. Fonts are in `.fonts` folder. You have to use `ls -a ` if you are looking for it.  :)

**Comment by HackerMan0611** [comment]
Thank you :+1: 
i will close this issue : )
